### ISSUE TITLE
the order of teams appears to change after 'update_skills'

### ISSUE THREAD

**Issue by mikeforls** [saulabs/trueskill#1]
Hi,

Thanks for going through the trouble of creating this code!

When I set team ranks in some arbitrary order, say, [3, 1, 2], I am not sure how to match the updated scores to the original teams. E.g. starting from equal mean assumptions, the above ordering of game ranks, leads to the first team on the list having the highest posterior mean.

I made a spec that is a reshuffle of one of your specs. I would think it should pass.

  describe 'standard rating and reverse order of wins' do

```
before :each do
  TrueSkill::FactorGraph.new(@teams, [2,1]).update_skills
end

it "should change second player's rating to [29.395832, 7.1714755]" do
  @teams[1][0].should eql_rating(29.395832, 7.1714755)
end

it "should change first player's rating to [20.6041679, 7.1714755]" do
  @teams[0][0].should eql_rating(20.6041679, 7.1714755)
end
```

  end

Thanks,
Mike.

**Comment by larskuhnt** [comment]
Hi Mike,

the teams and ranks should be in ascending order. Right now the ranks are used only to model draws, i.e:

``` ruby
TrueSkill::FactorGraph.new(@teams, [1,2,2,3])
```

You have to do the team-sorting prior to the trueskill calculation. I'll see if I have time to add a ranksorter in the next days.

L

**Comment by mikeforls** [comment]
Thanks Lars.

I've verified my concerns and your code works for me. So, the underdog can lose and all gets updated correctly. I just have to keep sorting the teams before each update so the rankings of the recent match are non-desreasing.

for:
   @teams = [
     [TrueSkill::Rating.new(20.0, 1.0, 1.0)],
     [TrueSkill::Rating.new(28.0, 1.0, 1.0)]
   ]
TrueSkill::FactorGraph.new(@teams, [1,2]).update_skills
gives:
(rdb:1) @teams[0][0]
#<Saulabs::TrueSkill::Rating:0xb74ace48 @tau=0.0833333333333333, @precision_mean=20.652474718693, @mean=20.3139198694157, @activity=1.0, @precision=1.01666615067174, @variance=0.983607056593037, @tau_squared=0.00694444444444444, @deviation=0.991769659040362>
(rdb:1) @teams[1][0]
#<Saulabs::TrueSkill::Rating:0xb74acd44 @tau=0.0833333333333333, @precision_mean=28.1475005135504, @mean=27.6860801305843, @activity=1.0, @precision=1.01666615067174, @variance=0.983607056593037, @tau_squared=0.00694444444444444, @deviation=0.991769659040362>

Thanks!
Mike.
